name             'windev'
maintainer       'Vassilis Rizopoulos'
maintainer_email 'var@zuehlke.com'
license          'all_rights'
description      'Configures Windows'
long_description 'Configures a Windows installation. Parameters include the list of Windows features to remove and data on the installer packages to be added'
version          '0.2.0'
depends 'windows'
